# Generated by Django 4.1.5 on 2023-02-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
