# Generated by Django 4.1.5 on 2023-02-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_reviews_reviewer_fooditem_image_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='type',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='type',
            field=models.ManyToManyField(to='restaurants.foodtype'),
        ),
    ]
