# Generated by Django 4.1.5 on 2023-02-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_foodtype_remove_fooditem_type_fooditem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='type',
        ),
        migrations.DeleteModel(
            name='FoodType',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
