# Generated by Django 4.1.5 on 2023-02-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_fooditem_type_delete_foodtype_fooditem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('banner_image_name', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
