# Generated by Django 4.1.5 on 2023-02-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_banners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banners',
            new_name='Banner',
        ),
    ]
