# Generated by Django 4.1.5 on 2023-02-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_rename_banners_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='banner_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
