# Generated by Django 4.1.5 on 2023-02-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_alter_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
