# Generated by Django 4.1.5 on 2023-02-10 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0011_fooditem_dislikes_fooditem_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='dislikers',
            field=models.ManyToManyField(blank=True, related_name='dislikers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
