# Generated by Django 4.1.5 on 2023-02-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_fooditem_dislikers_fooditem_likers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='dislikers',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='dislikes',
        ),
    ]
