# Generated by Django 4.1.5 on 2023-02-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_remove_fooditem_dislikers_remove_fooditem_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
