# Generated by Django 4.1.5 on 2023-02-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
    ]
