# Generated by Django 4.1.5 on 2023-02-12 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_remove_type_id_alter_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='type',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='food_type',
            field=models.ForeignKey(default='Entree', on_delete=django.db.models.deletion.CASCADE, to='restaurants.type'),
        ),
    ]
