# Generated by Django 4.1.5 on 2023-02-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_alter_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='uber',
            field=models.CharField(default='https://www.ubereats.com/', max_length=60),
        ),
    ]
