# Generated by Django 4.1.5 on 2023-02-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_restaurant_doodash_alter_restaurant_uber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='doodash',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='uber',
            field=models.CharField(default='', max_length=120),
        ),
    ]
