# Generated by Django 4.1.5 on 2023-02-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_alter_restaurant_doodash_alter_restaurant_uber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='doodash',
            new_name='doodashlink',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='uber',
            new_name='uberlink',
        ),
    ]
