# Generated by Django 4.1.5 on 2023-02-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_rename_doodash_restaurant_doodashlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='doodashlink',
            field=models.CharField(default='https://www.doordash.com/', max_length=120),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='uberlink',
            field=models.CharField(default='https://www.ubereats.com/', max_length=120),
        ),
    ]
