# Generated by Django 4.1.5 on 2023-02-15 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0023_alter_restaurant_doodashlink_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='doodashlink',
            new_name='doordashlink',
        ),
    ]
