# Generated by Django 4.1.5 on 2023-02-17 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0024_rename_doodashlink_restaurant_doordashlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='favoriters',
            field=models.ManyToManyField(blank=True, related_name='favoriters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='favorites',
            field=models.IntegerField(default=0),
        ),
    ]
