# Generated by Django 4.1.5 on 2023-02-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0026_deals'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='code',
            field=models.CharField(default='', max_length=256),
        ),
    ]
